services:

  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_DB=timetracker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p@ss!234

  djangorest-api:
    build: ./backend  
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres-db

  reactjs-ui:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - djangorest-api