# Generated by Django 5.0.2 on 2024-02-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnholdTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ref', models.DateTimeField(verbose_name='Date Reference')),
                ('duration_ms', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_onhold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetracker.onholdtimer')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetracker.project')),
            ],
        ),
        migrations.AddField(
            model_name='onholdtimer',
            name='main_timer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracker.timer'),
        ),
    ]
