# Generated by Django 5.0.2 on 2024-02-17 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='date_ref',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date Reference'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='duration_ms',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
