# Generated by Django 5.0.2 on 2024-02-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_alter_timer_date_ref_alter_timer_duration_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
