# Generated by Django 5.0.2 on 2024-02-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_timer_finished_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='finished_at',
            new_name='completed_at',
        ),
    ]
