# Generated by Django 5.0.2 on 2024-02-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0006_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
